defaultMarkdownHandler = "goldmark"

[goldmark]
  [goldmark.extensions]
    linkify = true
  [goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = "github"
    [goldmark.parser.attribute]
      block = true
      title = true
  [goldmark.renderer]
    unsafe = true

[highlight]
  anchorLineNos = true
  guessSyntax = false
  hl_Lines = ""
  hl_inline = false
  lineAnchors = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  noHl = false
  style = "emacs"
  tabWidth = 4

[tableOfContents]
  endLevel = 3
  ordered = false
  startLevel = 2
