name: Performance Test

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
      artifact_name:
        type: string
        required: true

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.branch}}

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          cache: true
          # Manually Update this `key`
          cache-key: "3.24.0"

      - name: Run performance tests
        working-directory: ./packages/fleather/example
        run: |
          flutter drive -d macos --driver=test_driver/performance_driver.dart --target=integration_test/scrolling_test.dart --profile
          flutter drive -d macos --driver=test_driver/performance_driver.dart --target=integration_test/editing_test.dart --profile

      - uses: actions/upload-artifact@v4
        with:
          name: ${{inputs.artifact_name}}
          path: ./packages/fleather/example/build/performance_timelines