name: Performance Test

on: 
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"
          cache: true
          # Manually Update this `key`
          cache-key: "20230512"
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Restore reference summary from cache
        id: performance_timelines_cache_restore
        uses: actions/cache/restore@v4
        with:
          path: packages/fleather/example/build/performance_timelines
          key: performance_timelines

      - if: steps.performance_timelines_cache_restore.outputs.cache-hit == 'true'
        run: mv packages/fleather/example/build/performance_timelines packages/fleather/example/build/reference_performance_timelines

      - name: Run performance tests
        working-directory: ./packages/fleather/example
        run: |
          flutter drive -d linux --driver=test_driver/performance_driver.dart --target=integration_test/scrolling_test.dart --profile
          flutter drive -d linux --driver=test_driver/performance_driver.dart --target=integration_test/editing_test.dart --profile
          dart run test_utils/analyze_performance_result.dart

      - name: Save reference summary
        if: github.ref == 'refs/heads/master'
        uses: actions/cache/save@v4
        with:
          path: build/performance_timelines
          key: performance_timelines