name: Performance Test

on: [push, pull_request, workflow_dispatch]

jobs:
  test_master:
    uses: ./.github/workflows/_run_performance_test.yaml
    with:
      branch: ${{github.ref}}
      artifact_name: master_performance_timelines

  test_current:
    uses: ./.github/workflows/_run_performance_test.yaml
    with:
      branch: ${{github.ref}}
      artifact_name: current_ref_performance_timelines

  analyze:
    needs: [test_master, test_current]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          cache: true
          # Manually Update this `key`
          cache-key: "3.24.0"

      - uses: actions/download-artifact@v4
        with:
          name: master_performance_timelines
      - run: mv packages/fleather/example/build/performance_timelines packages/fleather/example/build/reference_performance_timelines

      - uses: actions/download-artifact@v4
        with:
          name: current_ref_performance_timelines

      - name: Analyze results
        working-directory: ./packages/fleather/example
        run: dart run test_utils/analyze_performance_result.dart