include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**.g.dart'
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    always_declare_return_types: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    unawaited_futures: true
