format: true
use-escaping: true
nullable-getter: false
synthetic-package: false

arb-dir: lib/l10n
template-arb-file: app_en.arb

output-dir: lib/l10n/fleather_localizations
output-class: FleatherLocalizations
output-localization-file: fleather_localizations.g.dart

untranslated-messages-file: lib/l10n/untranslated.txt