format: true
use-escaping: true
synthetic-package: false

arb-dir: l10n
template-arb-file: app_en.arb

output-dir: lib/l10n
output-class: FleatherLocalizations
output-localization-file: fleather_localizations.g.dart

untranslated-messages-file: untranslated.txt